######################################## Log level ########################################
log:
  level: INFO

######################################## Entrypoints ########################################
# Redirect HTTP to HTTPS
# https://docs.traefik.io/routing/entrypoints/#redirection
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

  metrics:
    address: :8082

######################################## Enable API ########################################
api:
  # Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard: true

serversTransport:
  insecureSkipVerify: false

######################################## Providers ########################################
# https://docs.traefik.io/providers/docker/#exposedbydefault
# https://docs.traefik.io/providers/docker/#provider-configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false # Only expose explicitly enabled containers
  file:
    filename: "/etc/traefik/dyn.yml"

######################################## metrics ########################################
metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
