version: "3.9"
services:
  cloudflare-ddns:
    image: joshava/cloudflare-ddns:latest
    configs:
      - source: cloudflare-ddns-config
        target: /app/config.yaml
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 25M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 100
        window: 120s

configs:
  cloudflare-ddns-config:
    external: true
