global:
  resolve_timeout: 1m
  slack_api_url: '{{ SLACK_WEB_HOOK }}'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
    - channel: '{{ SLACK_CHANNEL }}'
      send_resolved: true
