{
 "title": "BMC overview",
 "tags": [
  "dell",
  "idrac"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(idrac_system_machine_info,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(idrac_system_machine_info{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "status-history",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "idrac_system_health{instance=~\"$instance\", job=\"$job\"}",
     "legendFormat": "{{instance}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Power",
   "type": "status-history",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "idrac_system_power_on{instance=~\"$instance\", job=\"$job\"}",
     "legendFormat": "{{instance}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Temperature CPU",
   "type": "timeseries",
   "description": "Top 10",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "topk(5, avg_over_time(idrac_sensors_temperature{instance=~\"$instance\",job=\"$job\", name=~\".+\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}: {{name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "avg(avg_over_time(idrac_sensors_temperature{instance=~\"$instance\",job=\"$job\", name=~\".+\"}[$__rate_interval]))",
     "legendFormat": "Mean: CPU temp"
    }
   ]
  },
  {
   "title": "Temperature other",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "topk(5, avg_over_time(idrac_sensors_temperature{instance=~\"$instance\",job=\"$job\", name!~\"CPU.+\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}: {{name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "avg by (name) (avg_over_time(idrac_sensors_temperature{instance=~\"$instance\",job=\"$job\", name!~\"CPU.+\"}[$__rate_interval]))",
     "legendFormat": "Mean: {{name}}"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time(idrac_sensors_fan_speed{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: {{name}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(avg_over_time(idrac_power_control_avg_consumed_watts{instance=~\"$instance\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Total power",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Power Supplies (output)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "max_over_time(idrac_power_supply_output_watts{instance=~\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}}: Output PSU-{{id}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Event log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Event Log (SEL)",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "idrac_sel_entry{job=\"$job\", instance=~\"$instance\"} * 1000 < ${__to} and \nidrac_sel_entry{job=\"$job\", instance=~\"$instance\"} * 1000 > ${__from}",
       "legendFormat": "{{id}} {{component}}:  {{message}}"
      }
     ]
    }
   ]
  }
 ]
}