groups:
- name: AllInstances
  rules:
  - alert: InstanceDown
    # Condition for alerting
    expr: up == 0
    for: 1m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'

- name: RaspPi
  rules:
  - alert: pihole_dns_request_count_zero
    expr: avg_over_time(pihole_dns_queries_all_types[5m]) == 0
    for: 5m
    annotations:
      title: 'PiHole DNS count for {{ $labels.hostname }} has been zero for 5 mins'
    labels:
      severity: 'high'
